// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod cosmonic {
    pub mod eventsourcing {
        /// Bank account events and serialization functions
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod bank_account {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Represents a state change that has occurred as a result of processing a command.
            #[derive(Clone)]
            pub struct Event {
                /// Event type identifier
                pub event_type: _rt::String,
                /// Serialized event data
                pub data: _rt::Vec<u8>,
                /// Event timestamp
                pub timestamp: u64,
                /// Event version for schema evolution
                pub version: u32,
            }
            impl ::core::fmt::Debug for Event {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Event")
                        .field("event-type", &self.event_type)
                        .field("data", &self.data)
                        .field("timestamp", &self.timestamp)
                        .field("version", &self.version)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Serialize, marshal, or encode a single event to its byte representation.
            pub fn serialize_event(event: &Event) -> Result<_rt::Vec<u8>, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let Event {
                        event_type: event_type0,
                        data: data0,
                        timestamp: timestamp0,
                        version: version0,
                    } = event;
                    let vec1 = event_type0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = data0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "cosmonic:eventsourcing/bank-account@0.0.1"
                    )]
                    unsafe extern "C" {
                        #[link_name = "serialize-event"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: i64,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: i64,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(
                            ptr1.cast_mut(),
                            len1,
                            ptr2.cast_mut(),
                            len2,
                            _rt::as_i64(timestamp0),
                            _rt::as_i32(version0),
                            ptr3,
                        )
                    };
                    let l5 = i32::from(*ptr3.add(0).cast::<u8>());
                    let result12 = match l5 {
                        0 => {
                            let e = {
                                let l6 = *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l7 = *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len8 = l7;
                                _rt::Vec::from_raw_parts(l6.cast(), len8, len8)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l9 = *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l10 = *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                _rt::string_lift(bytes11)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result12
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Deserialize, unmarshal, or decode a single event from its byte representation.
            pub fn deserialize_event(event: &[u8]) -> Result<Event, _rt::String> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 24 + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 24
                            + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = event;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "cosmonic:eventsourcing/bank-account@0.0.1"
                    )]
                    unsafe extern "C" {
                        #[link_name = "deserialize-event"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result15 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1.add(8).cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                let l7 = *ptr1
                                    .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *ptr1
                                    .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len9 = l8;
                                let l10 = *ptr1
                                    .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i64>();
                                let l11 = *ptr1
                                    .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i32>();
                                Event {
                                    event_type: _rt::string_lift(bytes6),
                                    data: _rt::Vec::from_raw_parts(l7.cast(), len9, len9),
                                    timestamp: l10 as u64,
                                    version: l11 as u32,
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l12 = *ptr1.add(8).cast::<*mut u8>();
                                let l13 = *ptr1
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len14 = l13;
                                let bytes14 = _rt::Vec::from_raw_parts(
                                    l12.cast(),
                                    len14,
                                    len14,
                                );
                                _rt::string_lift(bytes14)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result15
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod cosmonic {
        pub mod eventsourcing {
            /// Transaction Command Interface
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod transaction_command {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Command type specific to transactions
                #[derive(Clone)]
                pub struct Command {
                    /// Account ID to perform transaction on
                    pub account_id: _rt::String,
                    /// Transaction amount (positive for credit, negative for debit)
                    pub amount: i64,
                    /// Optional transaction description
                    pub description: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for Command {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Command")
                            .field("account-id", &self.account_id)
                            .field("amount", &self.amount)
                            .field("description", &self.description)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_command_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i64,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result2 = T::serialize_command(Command {
                        account_id: _rt::string_lift(bytes0),
                        amount: arg2,
                        description: match arg3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg5;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg4.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_command<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_command_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::deserialize_command(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let Command {
                                account_id: account_id3,
                                amount: amount3,
                                description: description3,
                            } = e;
                            let vec4 = (account_id3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                            *ptr2
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(amount3);
                            match description3 {
                                Some(e) => {
                                    *ptr2
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *ptr2
                                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *ptr2
                                        .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr5.cast_mut();
                                }
                                None => {
                                    *ptr2
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr2.add(8).cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_command<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = i32::from(
                                *arg0
                                    .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l3 {
                                0 => {}
                                _ => {
                                    let l4 = *arg0
                                        .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                }
                            }
                        }
                        _ => {
                            let l6 = *arg0.add(8).cast::<*mut u8>();
                            let l7 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Serialize the transaction command to its byte representation.
                    fn serialize_command(
                        command: Command,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    /// Deserialize the transaction command from its byte representation.
                    fn deserialize_command(
                        command: _rt::Vec<u8>,
                    ) -> Result<Command, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_cosmonic_eventsourcing_transaction_command_0_0_1_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "cosmonic:eventsourcing/transaction-command@0.0.1#serialize-command")]
                        unsafe extern "C" fn export_serialize_command(arg0 : * mut u8,
                        arg1 : usize, arg2 : i64, arg3 : i32, arg4 : * mut u8, arg5 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_serialize_command_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction-command@0.0.1#serialize-command")]
                        unsafe extern "C" fn _post_return_serialize_command(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_command::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "cosmonic:eventsourcing/transaction-command@0.0.1#deserialize-command")]
                        unsafe extern "C" fn export_deserialize_command(arg0 : * mut u8,
                        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_deserialize_command_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction-command@0.0.1#deserialize-command")]
                        unsafe extern "C" fn _post_return_deserialize_command(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_command::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_cosmonic_eventsourcing_transaction_command_0_0_1_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 24 + 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 24
                        + 4 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Transaction State Interface
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod transaction_state {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// State type specific to transactions
                #[derive(Clone)]
                pub struct State {
                    /// Account ID
                    pub id: _rt::String,
                    /// Current balance
                    pub balance: i64,
                    /// Whether the account is open
                    pub is_open: bool,
                    /// Customer ID
                    pub customer_id: _rt::String,
                    /// Account type
                    pub account_type: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for State {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("State")
                            .field("id", &self.id)
                            .field("balance", &self.balance)
                            .field("is-open", &self.is_open)
                            .field("customer-id", &self.customer_id)
                            .field("account-type", &self.account_type)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_initial_state_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::initial_state();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let State {
                        id: id2,
                        balance: balance2,
                        is_open: is_open2,
                        customer_id: customer_id2,
                        account_type: account_type2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(
                        balance2,
                    );
                    *ptr1
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match is_open2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    let vec4 = (customer_id2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len4;
                    *ptr1
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    match account_type2 {
                        Some(e) => {
                            *ptr1
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_initial_state<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = i32::from(
                        *arg0
                            .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    match l4 {
                        0 => {}
                        _ => {
                            let l5 = *arg0
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_serialize_state_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i64,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    let result3 = T::serialize_state(State {
                        id: _rt::string_lift(bytes0),
                        balance: arg2,
                        is_open: _rt::bool_lift(arg3 as u8),
                        customer_id: _rt::string_lift(bytes1),
                        account_type: match arg6 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg8;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg7.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        Ok(e) => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                            let vec5 = (e).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Err(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_serialize_state<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_deserialize_state_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::deserialize_state(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let State {
                                id: id3,
                                balance: balance3,
                                is_open: is_open3,
                                customer_id: customer_id3,
                                account_type: account_type3,
                            } = e;
                            let vec4 = (id3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                            *ptr2
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(balance3);
                            *ptr2
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match is_open3 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            let vec5 = (customer_id3.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            match account_type3 {
                                Some(e) => {
                                    *ptr2
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec6 = (e.into_bytes()).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr2
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr2
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr6.cast_mut();
                                }
                                None => {
                                    *ptr2
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr2.add(8).cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_deserialize_state<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = i32::from(
                                *arg0
                                    .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l5 {
                                0 => {}
                                _ => {
                                    let l6 = *arg0
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l6, l7, 1);
                                }
                            }
                        }
                        _ => {
                            let l8 = *arg0.add(8).cast::<*mut u8>();
                            let l9 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Get the initial state for a new aggregate with no events
                    fn initial_state() -> State;
                    /// Serialize the aggregate state to its byte representation.
                    fn serialize_state(
                        state: State,
                    ) -> Result<_rt::Vec<u8>, _rt::String>;
                    /// Deserialize the aggregate state from its byte representation.
                    fn deserialize_state(
                        state: _rt::Vec<u8>,
                    ) -> Result<State, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_cosmonic_eventsourcing_transaction_state_0_0_1_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "cosmonic:eventsourcing/transaction-state@0.0.1#initial-state")]
                        unsafe extern "C" fn export_initial_state() -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_initial_state_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction-state@0.0.1#initial-state")]
                        unsafe extern "C" fn _post_return_initial_state(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_initial_state::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "cosmonic:eventsourcing/transaction-state@0.0.1#serialize-state")]
                        unsafe extern "C" fn export_serialize_state(arg0 : * mut u8, arg1
                        : usize, arg2 : i64, arg3 : i32, arg4 : * mut u8, arg5 : usize,
                        arg6 : i32, arg7 : * mut u8, arg8 : usize,) -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_serialize_state_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) } }
                        #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction-state@0.0.1#serialize-state")]
                        unsafe extern "C" fn _post_return_serialize_state(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_serialize_state::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "cosmonic:eventsourcing/transaction-state@0.0.1#deserialize-state")]
                        unsafe extern "C" fn export_deserialize_state(arg0 : * mut u8,
                        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_deserialize_state_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction-state@0.0.1#deserialize-state")]
                        unsafe extern "C" fn _post_return_deserialize_state(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_deserialize_state::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_cosmonic_eventsourcing_transaction_state_0_0_1_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 8 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Transaction Handler Interface
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod transaction {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Event = super::super::super::super::cosmonic::eventsourcing::bank_account::Event;
                pub type Command = super::super::super::super::exports::cosmonic::eventsourcing::transaction_command::Command;
                pub type State = super::super::super::super::exports::cosmonic::eventsourcing::transaction_state::State;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_evolve_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i64,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                    arg9: *mut u8,
                    arg10: usize,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i64,
                    arg14: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    let len3 = arg10;
                    let bytes3 = _rt::Vec::from_raw_parts(arg9.cast(), len3, len3);
                    let len4 = arg12;
                    let result5 = T::evolve(
                        super::super::super::super::exports::cosmonic::eventsourcing::transaction_state::State {
                            id: _rt::string_lift(bytes0),
                            balance: arg2,
                            is_open: _rt::bool_lift(arg3 as u8),
                            customer_id: _rt::string_lift(bytes1),
                            account_type: match arg6 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len2 = arg8;
                                        let bytes2 = _rt::Vec::from_raw_parts(
                                            arg7.cast(),
                                            len2,
                                            len2,
                                        );
                                        _rt::string_lift(bytes2)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                        super::super::super::super::cosmonic::eventsourcing::bank_account::Event {
                            event_type: _rt::string_lift(bytes3),
                            data: _rt::Vec::from_raw_parts(arg11.cast(), len4, len4),
                            timestamp: arg13 as u64,
                            version: arg14 as u32,
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::exports::cosmonic::eventsourcing::transaction_state::State {
                                id: id7,
                                balance: balance7,
                                is_open: is_open7,
                                customer_id: customer_id7,
                                account_type: account_type7,
                            } = e;
                            let vec8 = (id7.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr6
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr6.add(8).cast::<*mut u8>() = ptr8.cast_mut();
                            *ptr6
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(balance7);
                            *ptr6
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match is_open7 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            let vec9 = (customer_id7.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr6
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr6
                                .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                            match account_type7 {
                                Some(e) => {
                                    *ptr6
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *ptr6
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *ptr6
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let vec11 = (e.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr6
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr6.add(8).cast::<*mut u8>() = ptr11.cast_mut();
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_evolve<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = i32::from(
                                *arg0
                                    .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l5 {
                                0 => {}
                                _ => {
                                    let l6 = *arg0
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l6, l7, 1);
                                }
                            }
                        }
                        _ => {
                            let l8 = *arg0.add(8).cast::<*mut u8>();
                            let l9 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_command_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i64,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                    arg9: *mut u8,
                    arg10: usize,
                    arg11: i64,
                    arg12: i32,
                    arg13: *mut u8,
                    arg14: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    let len3 = arg10;
                    let bytes3 = _rt::Vec::from_raw_parts(arg9.cast(), len3, len3);
                    let result5 = T::handle_command(
                        super::super::super::super::exports::cosmonic::eventsourcing::transaction_state::State {
                            id: _rt::string_lift(bytes0),
                            balance: arg2,
                            is_open: _rt::bool_lift(arg3 as u8),
                            customer_id: _rt::string_lift(bytes1),
                            account_type: match arg6 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len2 = arg8;
                                        let bytes2 = _rt::Vec::from_raw_parts(
                                            arg7.cast(),
                                            len2,
                                            len2,
                                        );
                                        _rt::string_lift(bytes2)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                        super::super::super::super::exports::cosmonic::eventsourcing::transaction_command::Command {
                            account_id: _rt::string_lift(bytes3),
                            amount: arg11,
                            description: match arg12 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len4 = arg14;
                                        let bytes4 = _rt::Vec::from_raw_parts(
                                            arg13.cast(),
                                            len4,
                                            len4,
                                        );
                                        _rt::string_lift(bytes4)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let vec10 = e;
                            let len10 = vec10.len();
                            let layout10 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec10.len()
                                    * (16 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let result10 = if layout10.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout10).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout10);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec10.into_iter().enumerate() {
                                let base = result10
                                    .add(i * (16 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::cosmonic::eventsourcing::bank_account::Event {
                                        event_type: event_type7,
                                        data: data7,
                                        timestamp: timestamp7,
                                        version: version7,
                                    } = e;
                                    let vec8 = (event_type7.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *base.add(0).cast::<*mut u8>() = ptr8.cast_mut();
                                    let vec9 = (data7).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>() = _rt::as_i64(timestamp7);
                                    *base
                                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i32>() = _rt::as_i32(version7);
                                }
                            }
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result10;
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let vec11 = (e.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr11.cast_mut();
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle_command<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base8 = l1;
                            let len8 = l2;
                            for i in 0..len8 {
                                let base = base8
                                    .add(i * (16 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                    let l5 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base7 = l5;
                                    let len7 = l6;
                                    _rt::cabi_dealloc(base7, len7 * 1, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base8,
                                len8 * (16 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                        }
                        _ => {
                            let l9 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l10 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l9, l10, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Evolve the aggregate's state by applying an event.
                    fn evolve(state: State, event: Event) -> Result<State, _rt::String>;
                    /// Handle the transaction command
                    fn handle_command(
                        state: State,
                        command: Command,
                    ) -> Result<_rt::Vec<Event>, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_cosmonic_eventsourcing_transaction_0_0_1_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "cosmonic:eventsourcing/transaction@0.0.1#evolve")] unsafe extern
                        "C" fn export_evolve(arg0 : * mut u8, arg1 : usize, arg2 : i64,
                        arg3 : i32, arg4 : * mut u8, arg5 : usize, arg6 : i32, arg7 : *
                        mut u8, arg8 : usize, arg9 : * mut u8, arg10 : usize, arg11 : *
                        mut u8, arg12 : usize, arg13 : i64, arg14 : i32,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_evolve_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                        arg11, arg12, arg13, arg14) } } #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction@0.0.1#evolve")]
                        unsafe extern "C" fn _post_return_evolve(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_evolve::<$ty > (arg0)
                        } } #[unsafe (export_name =
                        "cosmonic:eventsourcing/transaction@0.0.1#handle-command")]
                        unsafe extern "C" fn export_handle_command(arg0 : * mut u8, arg1
                        : usize, arg2 : i64, arg3 : i32, arg4 : * mut u8, arg5 : usize,
                        arg6 : i32, arg7 : * mut u8, arg8 : usize, arg9 : * mut u8, arg10
                        : usize, arg11 : i64, arg12 : i32, arg13 : * mut u8, arg14 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_handle_command_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13,
                        arg14) } } #[unsafe (export_name =
                        "cabi_post_cosmonic:eventsourcing/transaction@0.0.1#handle-command")]
                        unsafe extern "C" fn _post_return_handle_command(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_handle_command::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_cosmonic_eventsourcing_transaction_0_0_1_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 8 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_transaction_w_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction_command::__export_cosmonic_eventsourcing_transaction_command_0_0_1_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction_command); $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction_state::__export_cosmonic_eventsourcing_transaction_state_0_0_1_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction_state); $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction::__export_cosmonic_eventsourcing_transaction_0_0_1_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::cosmonic::eventsourcing::transaction);
    };
}
#[doc(inline)]
pub(crate) use __export_transaction_w_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:cosmonic:eventsourcing@0.0.1:transaction-w:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1003] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe7\x06\x01A\x02\x01\
A\x0b\x01B\x09\x01p}\x01r\x04\x0aevent-types\x04data\0\x09timestampw\x07versiony\
\x04\0\x05event\x03\0\x01\x01j\x01\0\x01s\x01@\x01\x05event\x02\0\x03\x04\0\x0fs\
erialize-event\x01\x04\x01j\x01\x02\x01s\x01@\x01\x05event\0\0\x05\x04\0\x11dese\
rialize-event\x01\x06\x03\0)cosmonic:eventsourcing/bank-account@0.0.1\x05\0\x01B\
\x0a\x01ks\x01r\x03\x0aaccount-ids\x06amountx\x0bdescription\0\x04\0\x07command\x03\
\0\x01\x01p}\x01j\x01\x03\x01s\x01@\x01\x07command\x02\0\x04\x04\0\x11serialize-\
command\x01\x05\x01j\x01\x02\x01s\x01@\x01\x07command\x03\0\x06\x04\0\x13deseria\
lize-command\x01\x07\x04\00cosmonic:eventsourcing/transaction-command@0.0.1\x05\x01\
\x01B\x0c\x01ks\x01r\x05\x02ids\x07balancex\x07is-open\x7f\x0bcustomer-ids\x0cac\
count-type\0\x04\0\x05state\x03\0\x01\x01@\0\0\x02\x04\0\x0dinitial-state\x01\x03\
\x01p}\x01j\x01\x04\x01s\x01@\x01\x05state\x02\0\x05\x04\0\x0fserialize-state\x01\
\x06\x01j\x01\x02\x01s\x01@\x01\x05state\x04\0\x07\x04\0\x11deserialize-state\x01\
\x08\x04\0.cosmonic:eventsourcing/transaction-state@0.0.1\x05\x02\x02\x03\0\0\x05\
event\x02\x03\0\x01\x07command\x02\x03\0\x02\x05state\x01B\x0d\x02\x03\x02\x01\x03\
\x04\0\x05event\x03\0\0\x02\x03\x02\x01\x04\x04\0\x07command\x03\0\x02\x02\x03\x02\
\x01\x05\x04\0\x05state\x03\0\x04\x01j\x01\x05\x01s\x01@\x02\x05state\x05\x05eve\
nt\x01\0\x06\x04\0\x06evolve\x01\x07\x01p\x01\x01j\x01\x08\x01s\x01@\x02\x05stat\
e\x05\x07command\x03\0\x09\x04\0\x0ehandle-command\x01\x0a\x04\0(cosmonic:events\
ourcing/transaction@0.0.1\x05\x06\x04\0*cosmonic:eventsourcing/transaction-w@0.0\
.1\x04\0\x0b\x13\x01\0\x0dtransaction-w\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
