package cosmonic:eventsourcing@0.0.1;

/// Event sourcer interface for handling commands and events
interface event-sourcer {
    use cosmonic:eventsourcing/bank-account.{event};

    append: func(aggregate-id: string, events: list<event>) -> result<list<list<u8>>, string>;
    get-events: func(aggregate-id: string) -> result<list<event>, string>;
    handle-command: func(aggregate-id: string, command: list<u8>) -> result<list<event>, string>;
}

/// Persistent storage layer
interface event-store {
    use cosmonic:eventsourcing/bank-account.{event};

    append-event: func(aggregate-id: string, event: list<u8>) -> result<_, string>;
    get-events: func(aggregate-id: string) -> result<list<list<u8>>, string>;
}

/// Business logic component world
world aggregate-w {
    import cosmonic:eventsourcing/bank-account;
    export cosmonic:eventsourcing/bank-account;
}

/// HTTP API Gateway world
world http-api-gateway-w {
    import event-sourcer;
    export wasi:http/incoming-handler@0.2.0;
}

/// Event sourcer system world
world event-sourcer-w {
    import cosmonic:eventsourcing/bank-account;
    import event-store;
    export event-sourcer;
}

/// Event store world
world event-store-w {
    export event-store;
}